In [2]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.893 seconds
All requested packages already installed.

In [3]:
import pandas as pd

In [16]:
df = pd.read_csv('./2_bookings.csv', encoding = 'windows-1251', sep = ';')

In [17]:
df.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [18]:
df.shape

(119390, 21)

In [19]:
df.dtypes

Hotel                            str
Is Canceled                    int64
Lead Time                      int64
arrival full date                str
Arrival Date Year              int64
Arrival Date Month               str
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                             str
Country                          str
Reserved Room Type               str
Assigned room type               str
customer type                    str
Reservation Status               str
Reservation status_date          str
dtype: object

In [20]:
df.columns = df.columns.str.lower()
df

,hotel,is canceled,lead time,arrival full date,arrival date year,arrival date month,arrival date week number,arrival date day of month,stays in weekend nights,stays in week nights,...,adults,children,babies,meal,country,reserved room type,assigned room type,customer type,reservation status,reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [21]:
df.columns

Index(['hotel', 'is canceled', 'lead time', 'arrival full date',
       'arrival date year', 'arrival date month', 'arrival date week number',
       'arrival date day of month', 'stays in weekend nights',
       'stays in week nights', 'stays total nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved room type', 'assigned room type',
       'customer type', 'reservation status', 'reservation status_date'],
      dtype='str')

In [25]:
df = df.rename(columns = {
    'is canceled':'is_canceled', 
    'lead time': 'lead_time',
    'arrival full date':'arrival_full_date',
    'arrival date year' : 'arrival_date_year',
    'arrival date month':'arrival_date_month', 
    'arrival date week number': 'arrival_date_week_number',
    'arrival date day of month':'arrival_date_day_of_month',
    'stays in weekend nights': 'stays_in_weekend_nights',
    'stays in week nights':'stays_in_week_nights',
    'stays total nights':'stays_total_nights', 
    'reserved room type':'reserved_room_type',
    'assigned room type':'assigned_room_type',
    'customer type':'customer_type',
    'reservation status':'reservation_status',
    'reservation status_date':'reservation_status_date'
})
df

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

In [31]:
df.groupby('country').agg({'is_canceled':'sum'}).sort_values(by = 'is_canceled', ascending = False).head(5)

         is_canceled
country
PRT            27519
GBR             2453
ESP             2177
FRA             1934
ITA             1333

In [37]:
top_fife_country = df\
    .groupby('country')\
    .agg({'is_canceled':'sum'})\
    .sort_values(by = 'is_canceled', ascending = False)\
    .reset_index()\
    .head(5)
top_fife_country

  country  is_canceled
0     PRT        27519
1     GBR         2453
2     ESP         2177
3     FRA         1934
4     ITA         1333

In [44]:
df.hotel.unique()

<StringArray>
['Resort Hotel', 'City Hotel']
Length: 2, dtype: str

In [56]:
count_nights = df\
    .groupby('hotel')\
    .agg({'stays_total_nights':'sum'})\
    .round(2)\
    .reset_index()
count_nights

          hotel  stays_total_nights
0    City Hotel              236256
1  Resort Hotel              173001

In [63]:
difference = (df['assigned_room_type']!=df['reserved_room_type']).sum()
difference

np.int64(14917)

In [113]:
year_2017 = df\
    .query('arrival_date_year==2017')\
    .groupby('arrival_date_month')\
    .size()\
    .sort_values(ascending = False)\
    .head(1)
year_2017

arrival_date_month
May    6313
dtype: int64

In [99]:
year_2016 = df\
    .query('arrival_date_year==2016')\
    .groupby('arrival_date_month')\
    .size()\
    .sort_values(ascending = False)\
    .head(1)
year_2016

arrival_date_month
October    6203
dtype: int64

In [100]:
year_2016 = df\
    .query('arrival_date_year==2016')\
    .groupby('arrival_date_month')\
    .size()
year_2016

arrival_date_month
April        5428
August       5063
December     3860
February     3891
January      2248
July         4572
June         5292
March        4824
May          5478
November     4454
October      6203
September    5394
dtype: int64

In [109]:
year_2016 = df\
    .query('arrival_date_year==2016')\
    ['arrival_date_month']\
    .value_counts()\
    .head(1)
year_2016

arrival_date_month
October    6203
Name: count, dtype: int64

In [133]:
off = (
    df[(df['hotel'] == 'City Hotel') & (df['is_canceled'] == 1)]
    .groupby(['arrival_date_year','arrival_date_month'])\
    .size()
)
off

arrival_date_year  arrival_date_month
2015               August                1232
                   December               668
                   July                   939
                   November               301
                   October               1321
                   September             1543
2016               April                 1539
                   August                1247
                   December              1072
                   February               930
                   January                438
                   July                  1043
                   June                  1720
                   March                 1108
                   May                   1436
                   November              1360
                   October               1947
                   September             1567
2017               April                 1926
                   August                1123
                   February               971
                   January               1044
                   July                  1324
                   June                  1808
                   March                 1278
                   May                   2217
dtype: int64

In [136]:
off = (
    df[(df['hotel'] == 'City Hotel') & (df['is_canceled'] == 1)]
    .groupby(['arrival_date_year'])['arrival_date_month']\
    .value_counts()
)
off

arrival_date_year  arrival_date_month
2015               September             1543
                   October               1321
                   August                1232
                   July                   939
                   December               668
                   November               301
2016               October               1947
                   June                  1720
                   September             1567
                   April                 1539
                   May                   1436
                   November              1360
                   August                1247
                   March                 1108
                   December              1072
                   July                  1043
                   February               930
                   January                438
2017               May                   2217
                   April                 1926
                   June                  1808
                   July                  1324
                   March                 1278
                   August                1123
                   January               1044
                   February               971
Name: count, dtype: int64

In [182]:
off = (
    df[(df['hotel'] == 'City Hotel') & (df['is_canceled'] == 1)]
    .groupby(['arrival_date_year'])['arrival_date_month']\
    .value_counts()\
    .groupby('arrival_date_year')
    .mean()
)
off

arrival_date_year
2015    1000.666667
2016    1283.916667
2017    1461.375000
Name: count, dtype: float64

In [138]:
off = (
    df[(df['hotel'] == 'City Hotel') & (df['is_canceled'] == 1)]
    .groupby(['arrival_date_year'])['arrival_date_month']\
    .value_counts()\
    .groupby('arrival_date_year')\
    .nlargest(1)
)
off

arrival_date_year  arrival_date_year  arrival_date_month
2015               2015               September             1543
2016               2016               October               1947
2017               2017               May                   2217
Name: count, dtype: int64

In [143]:
df[['adults','children','babies']].mean().idxmax()

'adults'

In [145]:
df[['adults','children','babies']].mean().max()

np.float64(1.8564033838679956)

In [148]:
df['total_children']=df['children']+df['babies']
df

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_children
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02,0.0
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02,0.0
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06,0.0
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07,0.0
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07,0.0
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07,0.0
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07,0.0

In [150]:
df.total_children.unique()

array([ 0.,  1.,  2., 10.,  3., nan,  9.])

In [157]:
df.groupby('hotel')['total_children'].mean().max().round(2)

np.float64(0.14)

In [160]:
df['has_kids'] = df['total_children'] > 0
df

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_children,has_kids
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02,0.0,False
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02,0.0,False
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06,0.0,False
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07,0.0,False
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07,0.0,False
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07,0.0,False
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07,0.0,False

In [161]:
df['has_kids'].unique()

array([False,  True])

In [178]:
outflow = df\
    .groupby('has_kids')['is_canceled']\
    .mean()\
    .nlargest(1)\
    .round(2)
outflow

has_kids
False    0.37
Name: is_canceled, dtype: float64

In [186]:
df['has_kids'] = df.total_children.astype(bool)
df

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_children,has_kids
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01,0.0,False
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02,0.0,False
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02,0.0,False
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06,0.0,False
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07,0.0,False
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07,0.0,False
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07,0.0,False
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07,0.0,False

In [187]:
df[['has_kids','is_canceled']].value_counts()

has_kids  is_canceled
False     0              69093
          1              40961
True      0               6073
          1               3263
Name: count, dtype: int64

In [188]:
df[['has_kids']].value_counts()

has_kids
False       110054
True          9336
Name: count, dtype: int64

In [189]:
df[['has_kids','is_canceled']].value_counts() / df[['has_kids']].value_counts() *100

has_kids  is_canceled
False     0              62.780998
          1              37.219002
True      0              65.049272
          1              34.950728
Name: count, dtype: float64

In [190]:
def has_kids(x):
    if x>0:
        return True
    else:
        return False

In [192]:
df['has_kids'] = df.total_children.apply(has_kids)